Add ingame "Ignore Mask Reaction" option
gamestabled/OoT3D_Randomizer pull request #500
Opened 2022-04-25 13:15 UTC by Kewlan

Causes NPCs to respond normally when wearing a mask. Does not apply when trading masks.

https://user-images.githubusercontent.com/5352197/165096330-9d6ea1d5-902a-4a00-a170-6ad315f25f2c.mp4

Also has some code improvements in `gfx_options.c`.

2022-04-28 23:19 UTC, HylianFreddy requested changes
The function you're hooking into receives the reactionSet as a parameter, so you can use that to recognize the DMT guard.

2022-04-28 23:19 UTC, HylianFreddy commented on code/src/savefile.c
> +    }
```suggestion
s8 SaveFile_GetIgnoreMaskReactionOption(u32 reactionSet) {
    // This option somehow breaks talking to the Kakariko Mountain Gate guard, so use a workaround
    if (reactionSet == 0x3C &&
        PLAYER->currentMask == 1 && (gSaveContext.infTable[7] & 0x80) == 0) {
        return 0;
    }
```
The DMT Gate guard uses reactionSet 0x3C.

2022-04-28 23:19 UTC, HylianFreddy commented on code/src/hooks.s
> +    bl SaveFile_GetIgnoreMaskReactionOption
```suggestion
    push {r0-r12, lr}
    cpy r0,r4
    bl SaveFile_GetIgnoreMaskReactionOption
```
The reactionSet is in r4

2022-04-29 09:40 UTC, Kewlan commented on code/src/savefile.c
> +    }
This is what I tried at first, but I think the reason it didn't work was because I copied `r1` instead of `r4` because of how it was called in Ghidra. Whoops.

2022-04-29 19:09 UTC, merged